// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// CreatePageRequest defines model for CreatePageRequest.
type CreatePageRequest struct {
	Ciphertext []byte `json:"ciphertext"`
	Id         PageID `json:"id"`
	Salt       []byte `json:"salt"`
	WriteToken string `json:"writeToken"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PageID defines model for PageID.
type PageID = string

// PageResponse defines model for PageResponse.
type PageResponse struct {
	Ciphertext []byte `json:"ciphertext"`
	Revision   int64  `json:"revision"`
	Salt       []byte `json:"salt"`
}

// RevisionResponse defines model for RevisionResponse.
type RevisionResponse struct {
	Revision int64 `json:"revision"`
}

// RotatePageRequest defines model for RotatePageRequest.
type RotatePageRequest struct {
	Ciphertext    []byte `json:"ciphertext"`
	NewId         PageID `json:"newId"`
	NewWriteToken string `json:"newWriteToken"`
	Salt          []byte `json:"salt"`
}

// UpdatePageRequest defines model for UpdatePageRequest.
type UpdatePageRequest struct {
	Ciphertext       []byte  `json:"ciphertext"`
	ExpectedRevision int64   `json:"expectedRevision"`
	NewWriteToken    *string `json:"newWriteToken,omitempty"`
	Salt             *[]byte `json:"salt,omitempty"`

	// WriteToken Legacy alternative to Authorization Bearer.
	WriteToken *string `json:"writeToken,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InsufficientStorage defines model for InsufficientStorage.
type InsufficientStorage = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PageCreateCmdJSONRequestBody defines body for PageCreateCmd for application/json ContentType.
type PageCreateCmdJSONRequestBody = CreatePageRequest

// PageUpdateCmdJSONRequestBody defines body for PageUpdateCmd for application/json ContentType.
type PageUpdateCmdJSONRequestBody = UpdatePageRequest

// PageRotateCmdJSONRequestBody defines body for PageRotateCmd for application/json ContentType.
type PageRotateCmdJSONRequestBody = RotatePageRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PageDeleteCmd request
	PageDeleteCmd(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PageCreateCmdWithBody request with any body
	PageCreateCmdWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PageCreateCmd(ctx context.Context, body PageCreateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PageFetchQry request
	PageFetchQry(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PageUpdateCmdWithBody request with any body
	PageUpdateCmdWithBody(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PageUpdateCmd(ctx context.Context, id PageID, body PageUpdateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PageRotateCmdWithBody request with any body
	PageRotateCmdWithBody(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PageRotateCmd(ctx context.Context, id PageID, body PageRotateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PageDeleteCmd(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageDeleteCmdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageCreateCmdWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageCreateCmdRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageCreateCmd(ctx context.Context, body PageCreateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageCreateCmdRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageFetchQry(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageFetchQryRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageUpdateCmdWithBody(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageUpdateCmdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageUpdateCmd(ctx context.Context, id PageID, body PageUpdateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageUpdateCmdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageRotateCmdWithBody(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageRotateCmdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PageRotateCmd(ctx context.Context, id PageID, body PageRotateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPageRotateCmdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPageDeleteCmdRequest generates requests for PageDeleteCmd
func NewPageDeleteCmdRequest(server string, id PageID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/pages/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPageCreateCmdRequest calls the generic PageCreateCmd builder with application/json body
func NewPageCreateCmdRequest(server string, body PageCreateCmdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPageCreateCmdRequestWithBody(server, "application/json", bodyReader)
}

// NewPageCreateCmdRequestWithBody generates requests for PageCreateCmd with any type of body
func NewPageCreateCmdRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/pages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPageFetchQryRequest generates requests for PageFetchQry
func NewPageFetchQryRequest(server string, id PageID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/pages/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPageUpdateCmdRequest calls the generic PageUpdateCmd builder with application/json body
func NewPageUpdateCmdRequest(server string, id PageID, body PageUpdateCmdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPageUpdateCmdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPageUpdateCmdRequestWithBody generates requests for PageUpdateCmd with any type of body
func NewPageUpdateCmdRequestWithBody(server string, id PageID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/pages/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPageRotateCmdRequest calls the generic PageRotateCmd builder with application/json body
func NewPageRotateCmdRequest(server string, id PageID, body PageRotateCmdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPageRotateCmdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPageRotateCmdRequestWithBody generates requests for PageRotateCmd with any type of body
func NewPageRotateCmdRequestWithBody(server string, id PageID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/pages/%s/rotate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PageDeleteCmdWithResponse request
	PageDeleteCmdWithResponse(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*PageDeleteCmdResponse, error)

	// PageCreateCmdWithBodyWithResponse request with any body
	PageCreateCmdWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageCreateCmdResponse, error)

	PageCreateCmdWithResponse(ctx context.Context, body PageCreateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageCreateCmdResponse, error)

	// PageFetchQryWithResponse request
	PageFetchQryWithResponse(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*PageFetchQryResponse, error)

	// PageUpdateCmdWithBodyWithResponse request with any body
	PageUpdateCmdWithBodyWithResponse(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageUpdateCmdResponse, error)

	PageUpdateCmdWithResponse(ctx context.Context, id PageID, body PageUpdateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageUpdateCmdResponse, error)

	// PageRotateCmdWithBodyWithResponse request with any body
	PageRotateCmdWithBodyWithResponse(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageRotateCmdResponse, error)

	PageRotateCmdWithResponse(ctx context.Context, id PageID, body PageRotateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageRotateCmdResponse, error)
}

type PageDeleteCmdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON429      *TooManyRequests
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PageDeleteCmdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PageDeleteCmdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PageDeleteCmdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PageCreateCmdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RevisionResponse
	JSON400      *BadRequest
	JSON409      *Conflict
	JSON429      *TooManyRequests
	JSON500      *InternalError
	JSON507      *InsufficientStorage
}

// Status returns HTTPResponse.Status
func (r PageCreateCmdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PageCreateCmdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PageCreateCmdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PageFetchQryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PageResponse
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r PageFetchQryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PageFetchQryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PageFetchQryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PageUpdateCmdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RevisionResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalError
	JSON507      *InsufficientStorage
}

// Status returns HTTPResponse.Status
func (r PageUpdateCmdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PageUpdateCmdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PageUpdateCmdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PageRotateCmdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RevisionResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON409      *Conflict
	JSON500      *InternalError
	JSON507      *InsufficientStorage
}

// Status returns HTTPResponse.Status
func (r PageRotateCmdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PageRotateCmdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PageRotateCmdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PageDeleteCmdWithResponse request returning *PageDeleteCmdResponse
func (c *ClientWithResponses) PageDeleteCmdWithResponse(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*PageDeleteCmdResponse, error) {
	rsp, err := c.PageDeleteCmd(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageDeleteCmdResponse(rsp)
}

// PageCreateCmdWithBodyWithResponse request with arbitrary body returning *PageCreateCmdResponse
func (c *ClientWithResponses) PageCreateCmdWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageCreateCmdResponse, error) {
	rsp, err := c.PageCreateCmdWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageCreateCmdResponse(rsp)
}

func (c *ClientWithResponses) PageCreateCmdWithResponse(ctx context.Context, body PageCreateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageCreateCmdResponse, error) {
	rsp, err := c.PageCreateCmd(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageCreateCmdResponse(rsp)
}

// PageFetchQryWithResponse request returning *PageFetchQryResponse
func (c *ClientWithResponses) PageFetchQryWithResponse(ctx context.Context, id PageID, reqEditors ...RequestEditorFn) (*PageFetchQryResponse, error) {
	rsp, err := c.PageFetchQry(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageFetchQryResponse(rsp)
}

// PageUpdateCmdWithBodyWithResponse request with arbitrary body returning *PageUpdateCmdResponse
func (c *ClientWithResponses) PageUpdateCmdWithBodyWithResponse(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageUpdateCmdResponse, error) {
	rsp, err := c.PageUpdateCmdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageUpdateCmdResponse(rsp)
}

func (c *ClientWithResponses) PageUpdateCmdWithResponse(ctx context.Context, id PageID, body PageUpdateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageUpdateCmdResponse, error) {
	rsp, err := c.PageUpdateCmd(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageUpdateCmdResponse(rsp)
}

// PageRotateCmdWithBodyWithResponse request with arbitrary body returning *PageRotateCmdResponse
func (c *ClientWithResponses) PageRotateCmdWithBodyWithResponse(ctx context.Context, id PageID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PageRotateCmdResponse, error) {
	rsp, err := c.PageRotateCmdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageRotateCmdResponse(rsp)
}

func (c *ClientWithResponses) PageRotateCmdWithResponse(ctx context.Context, id PageID, body PageRotateCmdJSONRequestBody, reqEditors ...RequestEditorFn) (*PageRotateCmdResponse, error) {
	rsp, err := c.PageRotateCmd(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePageRotateCmdResponse(rsp)
}

// ParsePageDeleteCmdResponse parses an HTTP response from a PageDeleteCmdWithResponse call
func ParsePageDeleteCmdResponse(rsp *http.Response) (*PageDeleteCmdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PageDeleteCmdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePageCreateCmdResponse parses an HTTP response from a PageCreateCmdWithResponse call
func ParsePageCreateCmdResponse(rsp *http.Response) (*PageCreateCmdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PageCreateCmdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RevisionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 507:
		var dest InsufficientStorage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON507 = &dest

	}

	return response, nil
}

// ParsePageFetchQryResponse parses an HTTP response from a PageFetchQryWithResponse call
func ParsePageFetchQryResponse(rsp *http.Response) (*PageFetchQryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PageFetchQryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PageResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePageUpdateCmdResponse parses an HTTP response from a PageUpdateCmdWithResponse call
func ParsePageUpdateCmdResponse(rsp *http.Response) (*PageUpdateCmdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PageUpdateCmdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RevisionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 507:
		var dest InsufficientStorage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON507 = &dest

	}

	return response, nil
}

// ParsePageRotateCmdResponse parses an HTTP response from a PageRotateCmdWithResponse call
func ParsePageRotateCmdResponse(rsp *http.Response) (*PageRotateCmdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PageRotateCmdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RevisionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 507:
		var dest InsufficientStorage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON507 = &dest

	}

	return response, nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fnfb9s2EP5XiFvfpsROm3Wr3tJ0BQK0W5e0GLDAGxjxLLGTSIU8pVED/e8DSVm2LLv+gdTtw95iS8c7",
	"fvfdd3fOAyS6KLVCRRbiByi54QUSGv/pHU/x4pX7S6BNjCxJagUx/F7y2wpZyVNkUqAiOZVojiEC6R6X",
	"nDKIQPECIQYpIAKDt5U0KCAmU2EENsmw4O7kJwanEMMPo3kgo/DUjlr/TdO4E2yplUUf2EsuLvG2Qkvu",
	"U6IVofJ/8rLMZcJdnKOP1gX7sKWvX43R5rJ1Elz2L32h7nguBTOt4yaCc62muUwOGIRDhPHcIBc1w3tp",
	"yTJtWJJxlaJgiVZJZQwqymsX4GttbqQQqA4PE68o00Z+9k5cLBfKVtOpTCQquiJteIqHi6p1yG4rTZzh",
	"fYIoUISwCI3iuT/ikDAFt8yiuUPD0LtvIvhN02tdKXFgTilNbOr9NhG81/otV3VbYvZwoVxyQpbLQtI8",
	"RxFkyEWrSJdIpj46mxKavluqSy82ijBF485uIvigZizEA+L5VlorVbpcAc1M9fxFzg1yQgf9gpBxIaR7",
	"mefvjC7RkEQL8ZTnFiMoF756gESWGRrCe2841abgBDHc1IQQzdCwZKRKXUal2FZrI7A83+7QT0YSvtf/",
	"BnlZetwsiv516AL+5Ggx9t4hk86HvvmIiZfYPtq7YYSzkv5yaOG1Vc7n/a/g929QpZRBfPL0lwgKqbrP",
	"zyPX8QiNS/7f12dHf/Gjz+OjF/8cTX58sgq3kPW9rrRj2g3eSSu16r0sFT0/BX8HWVQFxCfRoHy2ZsES",
	"lp3DVcleBfFla7AnHntfcF3cK2PUdMhaVfjpYodyVfjpzy8V4r6pDGGsLtq+z1WYfSjFITHD+xITQnH5",
	"JT4MSf5o2C2LYb8jvMGUJzXjue/5JO+QkWZni/2BvURuwgy9Qa2Wb7qhxNwdMKmMpPrKcSfAe+O9uQi6",
	"xueMwtfzGDKiMrQ4qaZ6eLHZWHX27oJNtWE6LAaoElOXhMKvCNZfSlLuTrySKs2xbI0ggjs0IWFwcjw+",
	"HjsodYmKlxJieHY8Pn4GXl8zH/eIl3LERSHVyB89epCiCXHlSF49HIs8pK6IvNa+8s/Oi7CILKwRT8en",
	"wzv5cSgc54eh0/HJumLsDhv1Jg1v9Gyz0Xw69xanmy264dAZPH2x2WB5kmsi+Gk83mzXn4oXSQTxdZ8+",
	"15NmEoGtioKbGmIIaDMe1sPKj0KUIfNZk5ZMKICEl/xG5u7ECIin1pHbvwOTJuototero52/0qmhs/QU",
	"8eTwC622tJoVYQKbscLj81KL+tHmxOGE1zTN8ibcDBh58mgBDFrrutk/8ZG2vN2CHAvbtzfZgofdpnxg",
	"4jqrn7exGu6mTbPI6pBNxtWSuC2QN3Bu0vQ42AlUimt4+Bopyf4w9VCcxo9Ghd7EuY4G3fq3sxTtKykd",
	"uh6DrcDdWxkiKCsaqv37DJlv3QuCxApesxtktnKAo2DcMt42aEauxbvfXKRi857vu18e2nySOxr5rjfM",
	"dpiLvp7qDOeurVRnfHjVqXyk+6vOd9qVd1XDb6pqgS3Dwmvb9mwrYudnV1sJ3cj4VWn5l+TdynRtxw57",
	"2NerneGe97127ADz/7XzDWpn2zH4jHQhE57ndZstPwT74rp4xbgSg7azqsK8R/cDcaiiyuQQw8jXSfvu",
	"w+z/LMGmibovwjDdTJr/BgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
