// Package provider contains the process composition providers generated by Wire.
package provider

import (
	"log/slog"

	"singlepage/internal/config"
	"singlepage/internal/handler/httpapi"
	"singlepage/internal/metrics"
	servicepage "singlepage/internal/service/page"
)

// ProvideHTTPServer creates the public HTTP server.
func ProvideHTTPServer(
	pages *servicepage.Service,
	applicationConfig config.Config,
	applicationMetrics *metrics.Metrics,
	logger *slog.Logger,
	includeFrontend bool,
) *httpapi.Server {
	return httpapi.New(pages, applicationConfig, applicationMetrics, logger, includeFrontend)
}
