// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"context"
	"log/slog"
	"singlepage/internal/config"
	"singlepage/internal/handler/httpapi"
	"singlepage/internal/metrics"
	"singlepage/internal/service/page"
)

// Injectors from wire.go:

// InitializePageService builds the transport-independent page graph.
func InitializePageService(ctx context.Context, storage config.Storage, logger *slog.Logger) (*page.Service, func(), error) {
	repository, cleanup, err := ProvidePageRepository(ctx, storage, logger)
	if err != nil {
		return nil, nil, err
	}
	service := ProvidePageService(repository, storage)
	return service, func() {
		cleanup()
	}, nil
}

// InitializeHTTPServer builds the public HTTP server dependency graph.
// The page providers intentionally remain explicit in both roots: a shared
// package-level wire.NewSet is copied into wire_gen.go and makes production
// binaries import Wire at runtime.
func InitializeHTTPServer(ctx context.Context, applicationConfig config.Config, applicationMetrics *metrics.Metrics, logger *slog.Logger, includeFrontend bool) (*httpapi.Server, func(), error) {
	storage := ProvideStorage(applicationConfig)
	repository, cleanup, err := ProvidePageRepository(ctx, storage, logger)
	if err != nil {
		return nil, nil, err
	}
	service := ProvidePageService(repository, storage)
	server := ProvideHTTPServer(service, applicationConfig, applicationMetrics, logger, includeFrontend)
	return server, func() {
		cleanup()
	}, nil
}
