// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class CreatePageRequest {
    "id": string;
    "salt": string;
    "ciphertext": string;
    "writeToken": string;

    /** Creates a new CreatePageRequest instance. */
    constructor($$source: Partial<CreatePageRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("salt" in $$source)) {
            this["salt"] = "";
        }
        if (!("ciphertext" in $$source)) {
            this["ciphertext"] = "";
        }
        if (!("writeToken" in $$source)) {
            this["writeToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatePageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatePageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatePageRequest($$parsedSource as Partial<CreatePageRequest>);
    }
}

export class MutationResponse {
    "revision": number;

    /** Creates a new MutationResponse instance. */
    constructor($$source: Partial<MutationResponse> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MutationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MutationResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MutationResponse($$parsedSource as Partial<MutationResponse>);
    }
}

export class Response {
    "revision": number;
    "salt": string;
    "ciphertext": string;

    /** Creates a new Response instance. */
    constructor($$source: Partial<Response> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = 0;
        }
        if (!("salt" in $$source)) {
            this["salt"] = "";
        }
        if (!("ciphertext" in $$source)) {
            this["ciphertext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Response instance from a string or object.
     */
    static createFrom($$source: any = {}): Response {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Response($$parsedSource as Partial<Response>);
    }
}

export class RotatePageRequest {
    "newId": string;
    "salt": string;
    "ciphertext": string;
    "newWriteToken": string;

    /** Creates a new RotatePageRequest instance. */
    constructor($$source: Partial<RotatePageRequest> = {}) {
        if (!("newId" in $$source)) {
            this["newId"] = "";
        }
        if (!("salt" in $$source)) {
            this["salt"] = "";
        }
        if (!("ciphertext" in $$source)) {
            this["ciphertext"] = "";
        }
        if (!("newWriteToken" in $$source)) {
            this["newWriteToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RotatePageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RotatePageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RotatePageRequest($$parsedSource as Partial<RotatePageRequest>);
    }
}

export class UpdatePageRequest {
    "expectedRevision": number;
    "ciphertext": string;
    "salt"?: string | null;
    "newWriteToken"?: string;

    /** Creates a new UpdatePageRequest instance. */
    constructor($$source: Partial<UpdatePageRequest> = {}) {
        if (!("expectedRevision" in $$source)) {
            this["expectedRevision"] = 0;
        }
        if (!("ciphertext" in $$source)) {
            this["ciphertext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdatePageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdatePageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdatePageRequest($$parsedSource as Partial<UpdatePageRequest>);
    }
}
