// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service adapts domain page operations to JSON-safe Wails methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreatePage(request: $models.CreatePageRequest, locator: string): $CancellablePromise<$models.MutationResponse> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.CreatePage", request, locator).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPage(id: string): $CancellablePromise<$models.Response> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.GetPage", id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListLocators returns usable native page locators in most-recently-opened order.
 */
export function ListLocators(): $CancellablePromise<string[]> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.ListLocators").then(($result: any) => {
        return $$createType2($result);
    });
}

export function RememberLocator(locator: string): $CancellablePromise<void> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.RememberLocator", locator);
}

export function RestoreLocator(): $CancellablePromise<string> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.RestoreLocator");
}

export function RotatePage(id: string, writeToken: string, request: $models.RotatePageRequest, locator: string): $CancellablePromise<$models.MutationResponse> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.RotatePage", id, writeToken, request, locator).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdatePage(id: string, writeToken: string, request: $models.UpdatePageRequest): $CancellablePromise<$models.MutationResponse> {
    return $Call.ByName("singlepage/cmd/app/internal/page.Service.UpdatePage", id, writeToken, request).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MutationResponse.createFrom;
const $$createType1 = $models.Response.createFrom;
const $$createType2 = $Create.Array($Create.Any);
